# Generated by Django 2.2 on 2019-08-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0006_auto_20181220_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delivery_boy',
            field=models.BooleanField(default=False, verbose_name='Is Delivery Boy'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Is Employee'),
        ),
    ]
