# Generated by Django 2.2 on 2019-08-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.Restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
                'unique_together': {('name', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('is_veg', models.BooleanField(default=True, verbose_name='Is Veg ?')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('inflation', models.IntegerField(default=0, verbose_name='Inflation')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Select Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Combo Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Combo Price')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('inflation', models.IntegerField(default=0, verbose_name='Inflation')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ImageField(blank=True, null=True, upload_to='combos/', verbose_name='Select Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('products', models.ManyToManyField(to='product.Product', verbose_name='Products')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.Restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
            },
        ),
    ]
