# Generated by Django 2.2 on 2019-04-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrestaurantrating',
            name='user',
        ),
    ]
