# Generated by Django 2.2 on 2019-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190731_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='inflation',
            field=models.IntegerField(default=0, verbose_name='Inflation'),
        ),
    ]
