# Generated by Django 2.2 on 2019-07-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20190724_2153'),
        ('product', '0005_auto_20190731_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Combo Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Combo Price')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('inflation', models.IntegerField(default=0, verbose_name='Inflation')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ImageField(default=None, upload_to='products/', verbose_name='Select Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('products', models.ManyToManyField(to='product.Product', verbose_name='Products')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.Restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
            },
        ),
    ]
