# Generated by Django 2.2 on 2019-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0008_auto_20190731_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Packaging Charge'),
        ),
    ]
