# Generated by Django 2.2 on 2019-08-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_packaging_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Select Image'),
        ),
        migrations.AlterField(
            model_name='productcombo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/', verbose_name='Select Image'),
        ),
    ]
