# Generated by Django 2.2 on 2019-08-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190801_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packaging_charge',
        ),
    ]
