# Generated by Django 2.2 on 2019-07-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190716_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_document', to=settings.AUTH_USER_MODEL),
        ),
    ]
