# Generated by Django 2.2 on 2019-04-24 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('business', '0002_auto_20190424_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('is_credit',
                 models.BooleanField(default=True, help_text='Is payment towards system?', verbose_name='Is Credit?')),
                ('payment_type',
                 models.CharField(choices=[('C', 'Cash On Delivery'), ('O', 'Online')], default='C', max_length=5,
                                  verbose_name='Payment Type')),
                ('payment_mode', models.CharField(
                    choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('PTM', 'PayTM'), ('C', 'Cash'),
                             ('IMJ', 'Instamojo'), ('PTMG', 'PayTM Payment Gateway')], default='C', max_length=5,
                    verbose_name='Payment Mode')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                  to='business.DeliveryBoys', verbose_name='Payment Accepted By')),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order',
                                            verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
            },
        ),
    ]
