# Generated by Django 2.2 on 2019-08-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('is_credit', models.BooleanField(default=True, help_text='Is payment towards system?', verbose_name='Is Credit?')),
                ('payment_type', models.CharField(choices=[('COD', 'Cash On Delivery'), ('O', 'Online'), ('UPI', 'Upi')], default='COD', max_length=5, verbose_name='Payment Type')),
                ('payment_mode', models.CharField(choices=[('PTM', 'PayTM'), ('C', 'Cash'), ('GP', 'Google Pay'), ('B', 'BHIM')], default='C', max_length=5, verbose_name='Payment Mode')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.Employee', verbose_name='Payment Accepted By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
            },
        ),
    ]
