# Generated by Django 2.2 on 2019-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190716_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('O', 'Online')], default='COD', max_length=5, verbose_name='Payment Type'),
        ),
    ]
