# Generated by Django 2.2 on 2019-07-16 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0003_auto_20190716_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='created_by',
        ),
    ]
