# Generated by Django 2.2 on 2019-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_orderpayment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_mode',
            field=models.CharField(choices=[('PTM', 'PayTM'), ('C', 'Cash'), ('GP', 'Google Pay'), ('B', 'BHIM')], default='C', max_length=5, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('O', 'Online'), ('UPI', 'Upi')], default='COD', max_length=5, verbose_name='Payment Type'),
        ),
    ]
