# Generated by Django 2.2 on 2019-04-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('H', 'Headquarters'), ('F', 'Franchise')], max_length=255,
                                          verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBoys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salary')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active ?')),
                ('start_time', models.TimeField(max_length=255, verbose_name='Start Time')),
                ('end_time', models.TimeField(max_length=255, verbose_name='End Time')),
                ('joined_on', models.DateField(blank=True, null=True, verbose_name='Join Date')),
                ('left_on', models.DateField(blank=True, null=True, verbose_name='Leave Date')),
            ],
            options={
                'verbose_name': 'Delivery Boy',
                'verbose_name_plural': 'Delivery Boys',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.Business',
                                               verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
    ]
