# Generated by Django 2.2 on 2019-04-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('business', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee',
                                    verbose_name='Employee Id'),
        ),
        migrations.AddField(
            model_name='deliveryboys',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee',
                                    verbose_name='Employee Id'),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.City',
                                    verbose_name='City'),
        ),
    ]
