# Generated by Django 2.2 on 2019-07-16 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0006_auto_20190716_1456'),
        ('transactions', '0002_auto_20190716_1456'),
        ('business', '0002_auto_20190424_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='business',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='employee',
        ),
        migrations.DeleteModel(
            name='DeliveryBoys',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
