# Generated by Django 2.2 on 2019-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0003_auto_20190716_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=27.988889, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=76.388333, max_digits=11, verbose_name='Longitude'),
        ),
    ]
