# Generated by Django 2.2 on 2019-07-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='discount',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Discount'),
        ),
    ]
