# Generated by Django 2.2 on 2019-08-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ribbon',
            field=models.CharField(blank=True, choices=[('Ex', 'Exclusive'), ('N', 'New')], max_length=255, null=True, verbose_name='Ribbon'),
        ),
    ]
