# Generated by Django 2.2 on 2019-07-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0002_restaurant_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount'),
        ),
    ]
