# Generated by Django 2.2 on 2019-07-15 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0004_auto_20190715_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
    ]
