# Generated by Django 2.2 on 2019-07-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0005_remove_restaurant_cuisine'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(
                    choices=[('As', 'Asian'), ('C', 'Cafe'), ('Ch', 'Chinese'), ('Co', 'Continental'),
                             ('Ff', 'Fast Food'), ('Fi', 'Finger Food'), ('G', 'Grill'), ('In', 'Indian'),
                             ('It', 'Italian'), ('Ja', 'Japanese'), ('Le', 'Lebanese'), ('Mi', 'Mithai'),
                             ('Mu', 'Mughlai'), ('Ni', 'North Indian'), ('Ra', 'Rajasthani'), ('Si', 'South Indian'),
                             ('Sf', 'Street Food'), ('Su', 'Sushi')], max_length=255, verbose_name='Cuisine')),
                ('restaurant',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.Restaurant',
                                   verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Cuisine',
                'verbose_name_plural': 'Restaurant Cuisines',
            },
        ),
    ]
