# Generated by Django 2.2 on 2019-07-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurantimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantimage',
            old_name='name',
            new_name='image_type',
        ),
    ]
