# Generated by Django 2.2 on 2019-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20190720_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Select Image'),
        ),
    ]
