# Generated by Django 2.2 on 2019-07-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0011_auto_20190720_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Select Image'),
        ),
    ]
