# Generated by Django 2.2 on 2019-07-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0012_auto_20190724_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Select Image'),
        ),
    ]
