# Generated by Django 2.2 on 2019-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_restaurant_packaging_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='gst',
            field=models.BooleanField(default=False, verbose_name='GST Charge'),
        ),
    ]
