# Generated by Django 2.2 on 2019-04-24 17:04

import django.db.models.deletion
import rest_framework.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestaurantRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(
                    validators=[rest_framework.compat.MaxValueValidator(5), rest_framework.compat.MinValueValidator(1)],
                    verbose_name='Rating')),
                ('restaurant',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.Restaurant',
                                   verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Rating',
                'verbose_name_plural': 'Restaurant Ratings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(
                    validators=[rest_framework.compat.MaxValueValidator(5), rest_framework.compat.MinValueValidator(1)],
                    verbose_name='Rating')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product',
                                              verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Rating',
                'verbose_name_plural': 'Product Ratings',
                'ordering': ['id'],
            },
        ),
    ]
