# Generated by Django 2.2 on 2019-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Charge'),
            preserve_default=False,
        ),
    ]
