# Generated by Django 2.2 on 2019-07-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_delivery_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Complaint'), ('F', 'Feedback'), ('S', 'Suggestion')], default='C', max_length=100, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('mobile', models.CharField(max_length=255, verbose_name='User mobile')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order', verbose_name='Order Id')),
            ],
            options={
                'verbose_name': 'Order Feedback',
                'verbose_name_plural': "Order Feedback's",
            },
        ),
    ]
