# Generated by Django 2.2 on 2019-07-16 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0005_orderfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboysorder',
            name='deliver_boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee',
                                    verbose_name='Delivery Boy'),
        ),
    ]
