# Generated by Django 2.2 on 2019-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0006_auto_20190716_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
