# Generated by Django 2.2 on 2019-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190801_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pe', 'Pending'), ('Ac', 'Accepted'), ('Pr', 'Preparing'), ('R', 'Ready'), ('Di', 'Dispatched'), ('D', 'Delivered'), ('C', 'Cancelled')], default='Pe', max_length=5, verbose_name='Order Status'),
        ),
    ]
