# Generated by Django 2.2 on 2019-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190807_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('Ac', 'Accepted'), ('Pr', 'Preparing'), ('O', 'On its way'), ('D', 'Delivered'), ('C', 'Cancelled')], default='N', max_length=5, verbose_name='Order Status'),
        ),
    ]
