# Generated by Django 2.2 on 2019-08-07 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190727_2221'),
        ('order', '0009_auto_20190807_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='employee.Employee', verbose_name='Delivery Boy'),
            preserve_default=False,
        ),
    ]
