# Generated by Django 2.2 on 2019-08-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_delivery_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.Employee', verbose_name='Delivery Boy'),
        ),
    ]
